class CreateTeamsTable < ActiveRecord::Migration
  def change
    create_table "Teams", id: false, force: :cascade do |t|
      t.integer   "yearID"
      t.text      "lgID"
      t.text      "teamID"
      t.text      "franchID"
      t.text      "divID"
      t.integer   "Rank"
      t.integer "G"
      t.integer "Ghome"
      t.integer "W"
      t.integer "L"
      t.text    "DivWin"
      t.text    "WCWin"
      t.text    "LgWin"
      t.text    "WSWin"
      t.integer "R"
      t.integer "AB"
      t.integer "H"
      t.integer "2B"
      t.integer "3B"
      t.integer "HR"
      t.integer "BB"
      t.integer "SO"
      t.integer "SB"
      t.integer "CS"
      t.integer "HBP"
      t.integer "SF"
      t.integer "RA"
      t.integer "ER"
      t.integer "ERA"
      t.integer "CG"
      t.integer "SHO"
      t.integer "SV"
      t.integer "IPouts"
      t.integer "HA"
      t.integer "HRA"
      t.integer "BBA"
      t.integer "SOA"
      t.integer "E"
      t.integer "DP"
      t.integer        "FP"
      t.text    "name"
      t.text    "park"
      t.integer "attendance"
      t.integer "BPF"
      t.integer "PPF"
      t.text    "teamIDBR"
      t.text    "teamIDlahman45"
      t.text    "teamIDretro"
      t.index ["divID"], name: "Teams_divID"
      t.index ["franchID"], name: "Teams_franchID"
      t.index ["yearID", "lgID", "teamID"], name: "Teams_Index_285058F1_D841_4142", unique: true
    end
  end
end
