class CreatePitchingsTable < ActiveRecord::Migration
  def change
    create_table :pitchings do |t|
      t.text    "playerID"
      t.integer "yearID"
      t.integer "stint"
      t.text    "teamID"
      t.text    "lgID"
      t.integer "W"
      t.integer "L"
      t.integer "G"
      t.integer "GS"
      t.integer "CG"
      t.integer "SHO"
      t.integer "SV"
      t.integer "IPouts"
      t.integer "H"
      t.integer "ER"
      t.integer "HR"
      t.integer "BB"
      t.integer "SO"
      t.float   "BAOpp"
      t.float   "ERA"
      t.integer "IBB"
      t.integer "WP"
      t.integer "HBP"
      t.integer "BK"
      t.integer "BFP"
      t.integer "GF"
      t.integer "R"
      t.integer "SH"
      t.integer "SF"
      t.integer "GIDP"
    end
  end
end
